// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX6GCES-HLFSLB4ACC24M26Cvqb2wsNRc',
    appId: '1:806170002014:web:de443f413119246dd4eacf',
    messagingSenderId: '806170002014',
    projectId: 'budgetcalculator-bfd7b',
    authDomain: 'budgetcalculator-bfd7b.firebaseapp.com',
    storageBucket: 'budgetcalculator-bfd7b.appspot.com',
    measurementId: 'G-55TY00CS0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CpXjblO9UPhI9h6x65_IYzstZRaqhOY',
    appId: '1:806170002014:android:f30fa03672af2094d4eacf',
    messagingSenderId: '806170002014',
    projectId: 'budgetcalculator-bfd7b',
    storageBucket: 'budgetcalculator-bfd7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CGFuegyz12Ge885BBqgb2h3UmPV1afU',
    appId: '1:806170002014:ios:491116aeeea84201d4eacf',
    messagingSenderId: '806170002014',
    projectId: 'budgetcalculator-bfd7b',
    storageBucket: 'budgetcalculator-bfd7b.appspot.com',
    iosBundleId: 'com.example.homeBudgetCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CGFuegyz12Ge885BBqgb2h3UmPV1afU',
    appId: '1:806170002014:ios:491116aeeea84201d4eacf',
    messagingSenderId: '806170002014',
    projectId: 'budgetcalculator-bfd7b',
    storageBucket: 'budgetcalculator-bfd7b.appspot.com',
    iosBundleId: 'com.example.homeBudgetCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX6GCES-HLFSLB4ACC24M26Cvqb2wsNRc',
    appId: '1:806170002014:web:854df56611a30bbfd4eacf',
    messagingSenderId: '806170002014',
    projectId: 'budgetcalculator-bfd7b',
    authDomain: 'budgetcalculator-bfd7b.firebaseapp.com',
    storageBucket: 'budgetcalculator-bfd7b.appspot.com',
    measurementId: 'G-VCK5E2NDHM',
  );
}
